### PR TITLE
layout issues has been fixed

### PR DESCRIPTION
**Pull request by AkshatSidharth**
Hey, AM1CODES I have added some tweaks and updates in the index.html, The whole layout has been fixed. Just merge my pull request and see for yourself. It has now become much more clean and appealing. Thank me later. Just one advice don't add any random card addition request. It distorts the remaining cards.

### CODE REVIEW

**Comment by AM1CODES** [comment]
I need more info on the changes, i cant just merge this cause i just fixed a small bug and the website already seems good to me

**Comment by AkshatSidharth** [comment]
My sincere apologies if I offended.

**Comment by AkshatSidharth** [comment]
I have send some screenshots for reference.

**Comment by AM1CODES** [comment]
> My sincere apologies if I offended.

No need to apologise mate. I will have  a look at it.

**Comment by AM1CODES** [comment]
Okay so i saw your changes and it has 19 conflicts at the moment, so i dont think we can merge it even after resolving the conflicts. So for the time being i dont think we need those changes, but the mobile version of this website is a little broken, so if you wish to work on that, go ahead. Again, thank you for your efforts. Appreciate it.

**Pull request closed without merging**
