### PR TITLE
Ananya

### PR DESCRIPTION
**Pull request by AnanyaNegi**

### CODE REVIEW

**Comment by AnanyaNegi** [comment]
> 
> 
> > _No description provided._
> 
> Hey, could you brief me about the changes that you made? Did you add a Pokemon card of tyrantrum?

yes

**Comment by AM1CODES** [comment]
> > > _No description provided._
> > 
> > 
> > Hey, could you brief me about the changes that you made? Did you add a Pokemon card of tyrantrum?
> 
> yes

I am sorry. There was some mistake on my end and hence i had to revert the merge. Could you please re fork it and make another PR? I am really sorry for the trouble.

**Comment by AnanyaNegi** [comment]
> 
> 
> > > > _No description provided._
> > > 
> > > 
> > > Hey, could you brief me about the changes that you made? Did you add a Pokemon card of tyrantrum?
> > 
> > 
> > yes
> 
> I am sorry. There was some mistake on my end and hence i had to revert the merge. Could you please re fork it and make another PR? I am really sorry for the trouble.

Yes sure

**Comment by AnanyaNegi** [comment]
Is the issue resolved or shoud i create pr again?

**Comment by AM1CODES** [comment]
> Is the issue resolved or should I create pr again?

Please Create another PR. As i reverted the changes the previous once are lost. Once again, i am sorry for the trouble.

**Comment by AnanyaNegi** [comment]
> 
> 
> > Is the issue resolved or should I create pr again?
> 
> Please Create another PR. As i reverted the changes the previous once are lost. Once again, i am sorry for the trouble.

No worries, I'll create another.

**Comment by AM1CODES** [comment]
> > > Is the issue resolved or should I create pr again?
> > 
> > 
> > Please Create another PR. As i reverted the changes the previous once are lost. Once again, i am sorry for the trouble.
> 
> No worries, I'll create another.

I suggest you refork it and then make the changes as i merged some other PRs recently. It would be easier for you.

**Pull request merged**
