### PR TITLE
4-pokemon update

### PR DESCRIPTION
**Pull request by 0Verlord-41**
I am really glad to work on this. As a pokemon fan, it brings back memories.

### CODE REVIEW

**Comment by 0Verlord-41** [comment]
I have added 4 new pokemon. I have included screenshots.
open1
open2

**Comment by AM1CODES** [comment]
But greninja already existed in the pokedex, can you reclone it once and add some other in its place?

**Comment by 0Verlord-41** [comment]
@AM1CODES bro I have checked the html code, but unable to find grey-ninja, will you check once, I might be wrong.

**Comment by AM1CODES** [comment]
It was there before but i guess some PR removed it. No problem, i merged yours. Thank you for contributing!

**Pull request merged**
