### PR TITLE
website responsive

### PR DESCRIPTION
**Pull request by srishtij2000**
I have made the website responsive . So kindly review it.

### CODE REVIEW

**Comment by AM1CODES** [comment]
It would be great  if you could add some screenshots for me to review.

**Comment by srishtij2000** [comment]
image

**Comment by srishtij2000** [comment]
image

**Comment by srishtij2000** [comment]
image

**Comment by srishtij2000** [comment]
I have uploaded the screenshots at different screen size . So kindly review it.

**Comment by AM1CODES** [comment]
This looks great to me! Thank you for doing this. I will merge it.

**Comment by srishtij2000** [comment]
Okay thank you

**Pull request merged**
