### PR TITLE
Fix Mobile Version

### PR DESCRIPTION
**Pull request by ashutoshkrris**
Add function to close the Navbar toggle on click.
Fix CSS of about.html page for mobile version

@AM1CODES, it won't break the code at all.. Please look into it.

### CODE REVIEW

**Comment by AM1CODES** [comment]
Can you brief me a little more on it? Because on mobile it seems to work perfectly. So i am not sure what changes did you make.

**Comment by ashutoshkrris** [comment]
On mobile version, when we click on any menu button, the the navbar toggle doesn't close automatically.
So, I fixed that to close automatically on click.

**Comment by AM1CODES** [comment]
Yes understood. The code looks good to me. I will merge it. Thanks for contributing.

**Comment by ashutoshkrris** [comment]
@AM1CODES Did you close without merging?

**Comment by AM1CODES** [comment]
Yes my bad. I am so sorry for the triuble. Could you please resend the PR. I closed it by mistake.

**Comment by AM1CODES** [comment]
Once again i apologize for all the trouble

**Comment by AM1CODES** [comment]
Merged.

**Comment by AM1CODES** [comment]
I was in a hurry so closed it by mistake. Sorry dude.

**Comment by ashutoshkrris** [comment]
> Once again i apologize for all the trouble

Hehe..
No worries
Thanks buddy.

**Pull request merged**
