### PR TITLE
Add raichu card

### PR DESCRIPTION
**Pull request by dms-yondy**
Added a card for raichu

### CODE REVIEW

**Comment by AM1CODES** [comment]
I request you to make a PR again and please read the code thoroughly. You actually added the card in middle of another card which broke the website. Also, do use an image thats similar in size to the other images. If you use images too large, it would not be possible to accomodate them properly

**Comment by dms-yondy** [comment]
I just checked the code in my pr and I didn't add my code between another card. I mean you can look at my commit it was fine. It was another pr that broke it. But I will fix the issue anyway 👍

**Comment by AM1CODES** [comment]
> I just checked the code in my pr and I didn't add my code between another card. I mean you can look at my commit it was fine. It was another pr that broke it. But I will fix the issue anyway 👍

Sorry, my bad. I messsed up the merging order.  Please make another PR. Sorry for the inconvenience.

**Comment by dms-yondy** [comment]
no problem, I have fixed the issue, I will make pr now :-)

**Pull request merged**
